### ISSUE TITLE
进阶路线图

### ISSUE THREAD

**Issue by dxd3678** [yangkun19921001/AVSample#3]
老哥，进阶路线图显示不全，可不可以重新上传一下

**Comment by yangkun19921001** [comment]
@dxd3678 我这边看是正常的呀！
这是原版的你试试 https://devyk.oss-cn-qingdao.aliyuncs.com/blog/20200702235045.jpg

**Comment by dxd3678** [comment]
这个正常啦，谢谢您了！




在2021年06月15日 14:58，DevYK 写道：

@dxd3678 我这边看是正常的呀！
这是原版的你试试 https://devyk.oss-cn-qingdao.aliyuncs.com/blog/20200702235045.jpg
